export const IPC = {
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONFIG_GET_ALL: 'config:get-all',
  PIPELINE_STATUS: 'pipeline:status',
  PIPELINE_PARTIAL_TEXT: 'pipeline:partial-text',
  PIPELINE_FINAL_TEXT: 'pipeline:final-text',
  PIPELINE_ERROR: 'pipeline:error',
  SHORTCUT_RECORD_START: 'shortcut:record-start',
  SHORTCUT_RECORD_STOP: 'shortcut:record-stop',
  KEYBOARD_EVENT: 'keyboard:event',  // Forward keyboard events from Swift to renderer
  PERMISSIONS_CHECK: 'permissions:check',
  PERMISSIONS_REQUEST: 'permissions:request',
  APP_GET_VERSION: 'app:get-version',
  AUDIO_CHUNK: 'audio:chunk',
  AUDIO_START: 'audio:start',
  AUDIO_STOP: 'audio:stop',
  AUDIO_THRESHOLD: 'audio:threshold',
  AUDIO_CAPTURE_ERROR: 'audio:capture-error',
  OVERLAY_SHOW: 'overlay:show',
  OVERLAY_HIDE: 'overlay:hide',
  OVERLAY_UPDATE: 'overlay:update',
  OPEN_SETTINGS: 'open:settings',
  DIALOG_SELECT_FOLDER: 'dialog:select-folder',
  SHELL_OPEN_PATH: 'shell:open-path',
  APP_GET_RUNNING_APPS: 'app:get-running-apps',
  DOCK_UPDATE_LOCK: 'dock:update-lock',
  HISTORY_UPDATED: 'history:updated'
} as const
