#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/build"
EXECUTABLE="$OUTPUT_DIR/SwiftKeyboardListener"

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "Building SwiftKeyboardListener..."

MIN_MACOS_VERSION="${MACOSX_DEPLOYMENT_TARGET:-13.0}"
ARCH="$(uname -m)"
if [ "$ARCH" != "arm64" ] && [ "$ARCH" != "x86_64" ]; then
    echo "Unsupported architecture: $ARCH"
    exit 1
fi

SWIFT_TARGET="$ARCH-apple-macos$MIN_MACOS_VERSION"
echo "Using Swift target: $SWIFT_TARGET"

# Generate MarkedEmbed.swift from the bundled markdown-core JS
BUNDLE_JS="$SCRIPT_DIR/Sources/markdown-bundle.js"
MARKED_EMBED="$SCRIPT_DIR/Sources/MarkedEmbed.swift"
if [ ! -f "$BUNDLE_JS" ]; then
    echo "Error: markdown-bundle.js not found. Run build-native.js instead of build.sh directly."
    exit 1
fi
echo "Embedding markdown bundle..."
{
  echo '// Auto-generated by build.sh — do not edit manually.'
  echo '// Bundled markdown-core (marked + sanitize + citations)'
  echo 'let _markedBundleSource = #"""'
  cat "$BUNDLE_JS"
  echo ''
  echo '"""#'
} > "$MARKED_EMBED"

# Compile the Swift sources
# Explicitly set deployment target so helper can run on older supported macOS versions
swiftc \
    -target "$SWIFT_TARGET" \
    -o "$EXECUTABLE" \
    "$SCRIPT_DIR/Sources/main.swift" \
    "$MARKED_EMBED" \
    -framework AppKit \
    -framework CoreFoundation \
    -framework CoreGraphics \
    -framework WebKit \
    -O

echo "Built successfully at: $EXECUTABLE"

# Verify the executable exists
if [ -f "$EXECUTABLE" ]; then
    echo "✓ SwiftKeyboardListener executable created"
else
    echo "✗ Failed to create executable"
    exit 1
fi
